### ISSUE TITLE
basics examples for loading images are referenced incorrectly

### ISSUE THREAD

**Issue by ProlificSwan** [photonstorm/phaser-examples#101]
Anyone attempting to load the main index.html in the examples folder and then run the basic examples will be met with an "unable to load" issue for the "basics" .js files. This can easily be fixed by adding a - to the .js files or removing the - from whatever is referring to those examples that way.

**Comment by Pajamaman** [comment]
Oops. Did it again. Ignore 34e80ee.

**Comment by Pajamaman** [comment]
Also see #83.

**Comment by ProlificSwan** [comment]
Thanks. Couldn't find the old one. Seems like this minor issue should be fixed by now?

**Comment by Pajamaman** [comment]
I don't think it's very high priority. @photonstorm mentioned dropping the whole web interface part anyways (https://github.com/photonstorm/phaser-examples/issues/89#issuecomment-128798471).
