### ISSUE TITLE
Question: (where) can the 'v2' demo format be found?

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser-examples#109]
The 'v2' demos - http://phaser.io/examples - are pretty impressive and offer a few features useful for developing locally.

Is this 'v2' structure available anywhere?

Even if not all the features can be supported it seems like many (including local edits) could be.

**Comment by photonstorm** [comment]
_All_ of the examples on the site come directly from this repo, using the exact same folder structure as this repo does as well (the examples site is constructed by scanning this repo for content).

What needs tidying up is removing all of the html / runner files from this repo, so it's just pure source code and assets, as I no longer want to have to maintain this. Would rather people view them online then use this repo to get at the actual source code.

**Comment by pnstickne** [comment]
Ref #112

**Comment by pnstickne** [comment]
I agree with removing the runner et. all (and even builds?) from this repository. Doing so would also lead to closing many of the issues. Ref #114

**Comment by photonstorm** [comment]
Yup - I'm all for doing this, but I need to update the web site first. The way it's currently coded it depends on lots of the files and the structure of this repo to function. If I nuke it all, I'll no longer be able to update the examples on the web site. So yes, I want to do it, and will do so, but there's some house-keeping that needs to happen first.
