### ISSUE TITLE
Fullscreen demos do not work on 'v2' demo site due to use of iframe

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser-examples#110]
Newer Chrome and FF have new(er?) Full Screen Mode security restrictions.

The containing iframe needs to have the `allowfullscreen` attribute present. The Full Screen demos work (barring other issues) once the attribute has been added.

Ref.
- http://www.allowfullscreen.com/
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

**Comment by photonstorm** [comment]
This has been added to the phaser site.
