### ISSUE TITLE
Demo "Display / Fullscreen Buttons" uses deprecated/removed API signature for events.

### ISSUE THREAD

**Issue by zimzat** [photonstorm/phaser-examples#127]
The following console messages are displayed:

> Phaser v2.4.3-dev | Pixi.js v2.2.8 | Canvas | WebAudio     http://phaser.io ♥♥♥
> embed.php:63 Uncaught TypeError: Cannot read property 'add' of undefined

The line this occurs on is:

``` javascript
    game.scale.enterFullScreen.add(onEnterFullScreen, this);
    game.scale.leaveFullScreen.add(onLeaveFullScreen, this);
```

One alternate way of making this work in the latest versions could be:

``` javascript
    game.scale.onFullScreenChange.add(onChangeFullScreen, this);

    game.input.onDown.add(gofull, this);

}

function onChangeFullScreen(scale) {

    if (scale.isFullScreen) {
        onEnterFullScreen();
    } else {
        onLeaveFullScreen();
    }

}
```

Alternatively the contents of the previous `onEnterFullScreen()` and `onLeaveFullScreen()` functions could be inlined to `onChangeFullScreen()`.

I'm willing to make the changes and submit a pull request if someone points the direction in which path would be preferred or can suggest an alternate.

**Comment by pnstickne** [comment]
Ref. https://github.com/photonstorm/phaser/issues/1988 - this is indeed a change to make.

**Comment by pnstickne** [comment]
I definitely think this change needs to be made, and hopefully account for older versions as well - but I'm not sure what Rich has in mind for the phaser-examples (sans-runner).

**Comment by zimzat** [comment]
Trying to keep examples working simultaneously with older and newer versions of Phaser is a tall order; one I would caution is way beyond the scope of this specific issue. At the very least the examples should always be working with the latest version otherwise as an official resource they become a minefield and could easily discourage new developers from using Phaser (a problem I personally ran into several times when getting started with Phaser). If I were to venture a thought toward how to make it work we'd probably need some way to say 'minimum supported version', a way to add revisions or git tags for specific older versions where the underlying feature changes, an interface into the website to change out the code based on which matches which, and many other moving parts. The effort may not be worth the gain.

I didn't think to check the main phaser repo for an issue on this error. It is poorly named but my search for 'fullscreen' would have caught it if I had thought to check there.

That issue and commit is from more than a month ago. What would it take to get it finalized and pushed into master?

**Comment by pierre-haessig** [comment]
I just got bitten by this. As of version 2.6.2, I get `TypeError: game.scale.enterFullScreen is undefined` raised from the `create` function. As such, the embedded example https://phaser.io/examples/v2/display/fullscreen-buttons is broken. Thanks @zimzat for sharing the new approach to deal with fullscreen events.
