### ISSUE TITLE
animation/creature dragon multiple.js not work

### ISSUE THREAD

**Issue by channingbreeze** [photonstorm/phaser-examples#133]
maybe the dragon.json is too large, 2.3M, what's that?

**Comment by ruslandzhumaev** [comment]
Crome console:
TypeError: c.Creature is not a function(…)
f.onload @ phaser.2.4.4.min.js:19

Creature pheonix is also too large.

**Comment by ppozniak** [comment]
Seems to be working right now

**Comment by ruslandzhumaev** [comment]
Yes, I believe the paths were not right.
