### ISSUE TITLE
"rocket launch" button is broken, can't run modified examples

### ISSUE THREAD

**Issue by zpmorgan** [photonstorm/phaser-examples#151]
The "Rocket Launch" button is totally broken.
For example, on this page: https://phaser.io/examples/v2/weapon/asteroids
When I click rocket launch to run an edited version, nothing changes and I get this in the console:

common.js:72Uncaught SyntaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin '//examples.phaser.io' in a call to 'postMessage'.

(anonymous function) @ common.js:72
dispatch @ jquery-2.0.3.min.js:5
y.handle @ jquery-2.0.3.min.js:5

Editing IDE_REMOTE="https://examples.phaser.io" makes the error go away, but the example still does not run.

**Comment by bpa** [comment]
When I tried changing IDE_REMOTE to match the protocol, I can get my changes to load.  I may have switched to http and then set it to http://examples.phaser.io.  Not sure if that makes a difference.

**Comment by zpmorgan** [comment]
I can confirm that it works with http but not https. Going to http://phaser.io/examples/v2/weapon/asteroids and setting IDE_REMOTE="http://examples.phaser.io" makes the modified code run.
