### ISSUE TITLE
examples.phaser.io’s server DNS address could not be found.

### ISSUE THREAD

**Issue by IsaacAbrahamson** [photonstorm/phaser-examples#162]
When trying to view an [example](https://phaser.io/examples/v2/games/defender), the example is grayed out, while the rest of the site works:

![image](https://cloud.githubusercontent.com/assets/17521691/25730731/006849b6-3105-11e7-8f99-1e14dd53ca61.png)

The exact error:
`Failed to load resource: net::ERR_NAME_NOT_RESOLVED https://examples.phaser.io/embed.php?f=games/defender.js`

**Comment by photonstorm** [comment]
Yes, we're under sustained DDoS attack and implementing measures to mitigate it at the moment. I'd strongly suggest maybe just trying again tomorrow I'm afraid.
