### ISSUE TITLE
DragonBones example not working

### ISSUE THREAD

**Issue by wayfu** [photonstorm/phaser-examples#47]
I think it's because the textures are img, not PIXI.texture...

**Comment by luckylooke** [comment]
I think this can be closed... I havent found any DragonBones example in actual version.

**Comment by rosshadden** [comment]
It looks like @wayfu meant to make this PR to [sprite-bones](https://github.com/jefree/sprite-bones), for the [phaser_dragonbones.js](https://github.com/jefree/sprite-bones/blob/master/src/phaser_dragonbones.js) file.
