### ISSUE TITLE
"Create From Objects" example doesn't display correctly in Phaser 2.2.* version

### ISSUE THREAD

**Issue by hightopo** [photonstorm/phaser-examples#75]
https://github.com/photonstorm/phaser-examples/blob/master/examples/tilemaps/create%20from%20objects.js

When i run this example with phaser below 2.1.X, everything is fine, but when I run this example with phaser 2.2.X on mac chrome, some sprite doesn't display whole, on mac safari when i move arrow a lot of sprites disappear, no exception is throw, so i am confuse, maybe some bugs in 2.2.X?

**Comment by Pajamaman** [comment]
It looks like photonstorm/phaser#1571 might have fixed this. Can this be closed?
