### ISSUE TITLE
GemMatch

### ISSUE THREAD

**Issue by cyberience** [photonstorm/phaser-examples#80]
Seems a bug around Gem Match, when matching 3, and does'nt complete until a second click on another object, and then swaps with gem at the top of the stack.
Then you have to click the matched set to make it clear.
Ill have a look if I can figure it out, and recommend back a fix.

**Comment by SzechuanSage** [comment]
I have a fix for this issue (see also issue #71) but I can't for the life of me see how to get the fix into github. If some kind soul can help me out I will be happy to upload the fix and discuss it.

**Comment by photonstorm** [comment]
Fork the repo. Make the change. Come back to this repo and submit a Pull Request.
