### ISSUE TITLE
seven basic examples are with link broken

### ISSUE THREAD

**Issue by arcanosam** [photonstorm/phaser-examples#83]
Hi all.

All seven basics examples are with link broken

The problem is in _./examples/_site/examples.json_
All seven file names area define with a '**-**' between number and title, like

_"file": "01+__-__+load+an+image.js"_

but the correct is: _"file":"01+load+an+image.js"_

I change **examples.json**, but other option is rename the basics js files...

I expect this help and sorry if it's duplicate, I look but not found anyone told about that...

See ya

Samuel

**Comment by mikaturunen** [comment]
Fixed in the references Pull Request.
