### ISSUE TITLE
Most examples don't function well on mobile, if at all

### ISSUE THREAD

**Issue by gingerbeardman** [photonstorm/phaser-examples#85]
Please make all examples work well on mobile.

**Comment by photonstorm** [comment]
So I turned on my iPad, picked 1 random example from each section (that I knew didn't use cursor key controls) and they all ran. I doubt there are many at all that literally don't work on mobile (the keyboard input ones spring to mind for obvious reasons, or ones that use APIs mobiles just don't have like full screen).

The only real issue with them are the ones that use cursor keys to control them - of which there are quite a few (especially in the physics sections) But there's no way we're adding virtual pad controls to every example that needs cursors though. It would pointlessly bulk out the code.

**Comment by gingerbeardman** [comment]
Hi. Yes, I filled this on the back of the new Box2D examples. 

Cursor controls are an issue (instead of gesture or touch controls; virtual d-pad is a bad idea)

But also the canvas size used in the examples quite large. I'm on my iPhone right now and most examples not very usable add they don't fit on screen. Even those that don't require any input. 

What could be done to address these issues? 

1. Use a template for the demos that caters for different screen sizes.
2. Add gesture support. 

Maybe one ery to consider for V3?

**Comment by pnstickne** [comment]
@photonstorm The old Phaser example site had external arrow buttons (I don't think I ever saw the work, however) -

Would it be worthwhile to consider adding back in some 'external virtual controls' and can be activated (like those on-screen keyboards)?
