### ISSUE TITLE
This repo seems to be broken since the release of 2.3.0?

### ISSUE THREAD

**Issue by fiso** [photonstorm/phaser-examples#89]
For instance, the examples try to load _site/js/phaser.js - which does not exist. Just clone the repo and try to look at the examples and you'll note how they don't work.

**Comment by photonstorm** [comment]
Yes I'll tidy it up and remove all of the local test stuff. Really I want this repo to be just the source code now, I don't have time to maintain it and the main site.

**Comment by Pajamaman** [comment]
How do you want to handle updating the examples? If I find one that's broken at http://phaser.io/examples, which is currently using 2.4.3-dev, should I fix it in this repo even though it's still on 2.4.2? Or do you want to fix them all at once?

**Comment by photonstorm** [comment]
Feel free to fix them directly on the master branch. Just don't bother fixing the html files or example runner, as I will be removing it all soon - just fix the js files only. Do one at a time and submit a PR (or one set at a time - don't just bombard me with 100 updated files or something)

**Comment by Pajamaman** [comment]
Ok, it's just kind of confusing because I can fix it to run on the main website or I can fix it to run locally on my own branch of this repo, but not both, unless I update the version of Phaser this repo uses, but you don't want to do that, so I have to change it, but I won't commit it.
