### ISSUE TITLE
Examples not loading on chromium

### ISSUE THREAD

**Issue by luckylooke** [photonstorm/phaser-examples#97]
Console error: 

Mixed Content: The page at 'https://phaser.io/examples/v2/groups/bring-a-group-to-top' was loaded over HTTPS, but requested an insecure resource 'http://examples.phaser.io/embed.php?f=groups/bring+a+group+to+top.js'. This request has been blocked; the content must be served over HTTPS.

what can I try?

**Comment by tgeorge91** [comment]
I noticed this yesterday as well. Get rid of the https in your url and just do http and it'll work, until this is fixed. http://phaser.io/examples/v2/groups/bring-a-group-to-top should work.

**Comment by luckylooke** [comment]
Youre right! I dont know how did I get to https.. chromium doesnt show protocol, but when I force http.. it works, thank you ;)

**Comment by photonstorm** [comment]
Just closing this off as I fixed it a while ago.
